name: Sync to Repo 1

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo 2
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.REPO1_TOKEN }}

      - name: Push vers repo 1
        if: github.repository != 'EpitechPGE2-2025/G-NWP-400-MLH-4-1-myteams-3'
        run: |
          git remote add repo1 git@github.com:EpitechPGE2-2025/G-NWP-400-MLH-4-1-myteams-3.git
          git push repo1 main
